### ISSUE TITLE
Is this mod still in active development?

### ISSUE THREAD

**Issue by Jacky1356400** [Lomeli12/ElementalCreepers-Rebooted#27]
As the title said, I would like to know if this mod is still being maintained or not. If not, I am interested in porting this mod for more modern versions of MC (1.10.2 - 1.12).

**Comment by Lomeli12** [comment]
I haven't really done any modding due to work. Feel fork and update the mod for your own personal use (that's why this repo is public, so others can work on it if they want to), but to distribute it publicly, you need to ask xSmallDeadGuyx for permission. It's still technically his mod, I just had permission to distribute my code and jars.

**Comment by Jacky1356400** [comment]
Ah right, I'll have a look into it.

**Comment by Jacky1356400** [comment]
So, is there any ways I can contact xSmallDeadGuyx? I've tried to find him on Minecraft Forum but...
![](https://i.gyazo.com/5d36ad73f9d85b62050985c0f0ffa06c.png)
Last active time is a year ago, not sure if there's any other ways I can get hold of him.

**Comment by Lomeli12** [comment]
His github? It at least has his email https://github.com/xSmallDeadGuyx

**Comment by Jacky1356400** [comment]
Ah yeah, good shout. I shall email him and see if I get a response or not.
